name: Generate README

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/readme.tpl"
          writeTo: "README.md"

      - name: Commit and Push
        uses: endbug/add-and-commit@v9
        with:
          message: "chore: generate readme"
